var countryCodes = {
  "United Arab Emirates":"ARE",
  "Afghanistan":"AFG",
  "Antigua and Barbuda":"ATG",
  "Anguilla":"AIA",
  "Albania":"ALB",
  "Armenia":"ARM",
  "Netherlands Antilles":"ANT",
  "Angola":"AGO",
  "Antarctica":"ATA",
  "Argentina":"ARG",
  "American Samoa":"ASM",
  "Austria":"AUT",
  "Australia":"AUS",
  "Aruba":"ABW",
  "Åland":"ALA",
  "Azerbaijan":"AZE",
  "Bosnia and Herzegovina":"BIH",
  "Barbados":"BRB",
  "Bangladesh":"BGD",
  "Belgium":"BEL",
  "Burkina Faso":"BFA",
  "Bulgaria":"BGR",
  "Bahrain":"BHR",
  "Burundi":"BDI",
  "Benin":"BEN",
  "Saint Barthélemy":"BLM",
  "Bermuda":"BMU",
  "Brunei":"BRN",
  "Bolivia":"BOL",
  "Bonaire":"BES",
  "Brazil":"BRA",
  "Bahamas":"BHS",
  "Bhutan":"BTN",
  "Bouvet Island":"BVT",
  "Botswana":"BWA",
  "Belarus":"BLR",
  "Belize":"BLZ",
  "Canada":"CAN",
  "Cocos [Keeling] Islands":"CCK",
  "Democratic Republic of the Congo":"COD",
  "Central African Republic":"CAF",
  "Republic of the Congo":"COG",
  "Switzerland":"CHE",
  "Ivory Coast":"CIV",
  "Cook Islands":"COK",
  "Chile":"CHL",
  "Cameroon":"CMR",
  "China":"CHN",
  "Colombia":"COL",
  "Costa Rica":"CRI",
  "Cuba":"CUB",
  "Cape Verde":"CPV",
  "Curacao":"CUW",
  "Christmas Island":"CXR",
  "Cyprus":"CYP",
  "Czechia":"CZE",
  "Germany":"DEU",
  "Djibouti":"DJI",
  "Denmark":"DNK",
  "Dominica":"DMA",
  "Dominican Republic":"DOM",
  "Algeria":"DZA",
  "Ecuador":"ECU",
  "Estonia":"EST",
  "Egypt":"EGY",
  "Western Sahara":"ESH",
  "Eritrea":"ERI",
  "Spain":"ESP",
  "Ethiopia":"ETH",
  "Finland":"FIN",
  "Fiji":"FJI",
  "Falkland Islands":"FLK",
  "Micronesia":"FSM",
  "Faroe Islands":"FRO",
  "France":"FRA",
  "Gabon":"GAB",
  "United Kingdom":"GBR",
  "Grenada":"GRD",
  "Georgia":"GEO",
  "French Guiana":"GUF",
  "Guernsey":"GGY",
  "Ghana":"GHA",
  "Gibraltar":"GIB",
  "Greenland":"GRL",
  "Gambia":"GMB",
  "Guinea":"GIN",
  "Guadeloupe":"GLP",
  "Equatorial Guinea":"GNQ",
  "Greece":"GRC",
  "South Georgia and the South Sandwich Islands":"SGS",
  "Guatemala":"GTM",
  "Guam":"GUM",
  "Guinea-Bissau":"GNB",
  "Guyana":"GUY",
  "Hong Kong":"HKG",
  "Heard Island and McDonald Islands":"HMD",
  "Honduras":"HND",
  "Croatia":"HRV",
  "Haiti":"HTI",
  "Hungary":"HUN",
  "Indonesia":"IDN",
  "Ireland":"IRL",
  "Israel":"ISR",
  "Isle of Man":"IMN",
  "India":"IND",
  "British Indian Ocean Territory":"IOT",
  "Iraq":"IRQ",
  "Iran":"IRN",
  "Iceland":"ISL",
  "Italy":"ITA",
  "Jersey":"JEY",
  "Jamaica":"JAM",
  "Jordan":"JOR",
  "Japan":"JPN",
  "Kenya":"KEN",
  "Kyrgyzstan":"KGZ",
  "Cambodia":"KHM",
  "Kiribati":"KIR",
  "Comoros":"COM",
  "Saint Kitts and Nevis":"KNA",
  "North Korea":"PRK",
  "South Korea":"KOR",
  "Kuwait":"KWT",
  "Cayman Islands":"CYM",
  "Kazakhstan":"KAZ",
  "Laos":"LAO",
  "Lebanon":"LBN",
  "Saint Lucia":"LCA",
  "Liechtenstein":"LIE",
  "Sri Lanka":"LKA",
  "Liberia":"LBR",
  "Lesotho":"LSO",
  "Lithuania":"LTU",
  "Luxembourg":"LUX",
  "Latvia":"LVA",
  "Libya":"LBY",
  "Morocco":"MAR",
  "Monaco":"MCO",
  "Moldova":"MDA",
  "Montenegro":"MNE",
  "Saint Martin":"MAF",
  "Madagascar":"MDG",
  "Marshall Islands":"MHL",
  "Macedonia":"MKD",
  "Mali":"MLI",
  "Myanmar [Burma]":"MMR",
  "Mongolia":"MNG",
  "Macao":"MAC",
  "Northern Mariana Islands":"MNP",
  "Martinique":"MTQ",
  "Mauritania":"MRT",
  "Montserrat":"MSR",
  "Malta":"MLT",
  "Mauritius":"MUS",
  "Maldives":"MDV",
  "Malawi":"MWI",
  "Mexico":"MEX",
  "Malaysia":"MYS",
  "Mozambique":"MOZ",
  "Namibia":"NAM",
  "New Caledonia":"NCL",
  "Niger":"NER",
  "Norfolk Island":"NFK",
  "Nigeria":"NGA",
  "Nicaragua":"NIC",
  "Netherlands":"NLD",
  "Norway":"NOR",
  "Nepal":"NPL",
  "Nauru":"NRU",
  "Niue":"NIU",
  "New Zealand":"NZL",
  "Oman":"OMN",
  "Panama":"PAN",
  "Peru":"PER",
  "French Polynesia":"PYF",
  "Papua New Guinea":"PNG",
  "Philippines":"PHL",
  "Pakistan":"PAK",
  "Poland":"POL",
  "Saint Pierre and Miquelon":"SPM",
  "Pitcairn Islands":"PCN",
  "Puerto Rico":"PRI",
  "Palestine":"PSE",
  "Portugal":"PRT",
  "Palau":"PLW",
  "Paraguay":"PRY",
  "Qatar":"QAT",
  "Réunion":"REU",
  "Romania":"ROU",
  "Serbia":"SRB",
  "Russia":"RUS",
  "Rwanda":"RWA",
  "Saudi Arabia":"SAU",
  "Solomon Islands":"SLB",
  "Seychelles":"SYC",
  "Sudan":"SDN",
  "Sweden":"SWE",
  "Singapore":"SGP",
  "Saint Helena":"SHN",
  "Slovenia":"SVN",
  "Svalbard and Jan Mayen":"SJM",
  "Slovakia":"SVK",
  "Sierra Leone":"SLE",
  "San Marino":"SMR",
  "Senegal":"SEN",
  "Somalia":"SOM",
  "Suriname":"SUR",
  "South Sudan":"SSD",
  "São Tomé and Príncipe":"STP",
  "El Salvador":"SLV",
  "Sint Maarten":"SXM",
  "Syria":"SYR",
  "Swaziland":"SWZ",
  "Turks and Caicos Islands":"TCA",
  "Chad":"TCD",
  "French Southern Territories":"ATF",
  "Togo":"TGO",
  "Thailand":"THA",
  "Tajikistan":"TJK",
  "Tokelau":"TKL",
  "East Timor":"TLS",
  "Turkmenistan":"TKM",
  "Tunisia":"TUN",
  "Tonga":"TON",
  "Turkey":"TUR",
  "Trinidad and Tobago":"TTO",
  "Tuvalu":"TUV",
  "Taiwan":"TWN",
  "Tanzania":"TZA",
  "Ukraine":"UKR",
  "Uganda":"UGA",
  "U.S. Minor Outlying Islands":"UMI",
  "United States":"USA",
  "Uruguay":"URY",
  "Uzbekistan":"UZB",
  "Vatican City":"VAT",
  "Saint Vincent and the Grenadines":"VCT",
  "Venezuela":"VEN",
  "British Virgin Islands":"VGB",
  "U.S. Virgin Islands":"VIR",
  "Vietnam":"VNM",
  "Vanuatu":"VUT",
  "Wallis and Futuna":"WLF",
  "Samoa":"WSM",
  "Kosovo":"XKX",
  "Yemen":"YEM",
  "Mayotte":"MYT",
  "South Africa":"ZAF",
  "Zambia":"ZMB",
  "Zimbabwe":"ZWE"
};